name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Dummy install step
        run: echo "No package.json found — skipping npm install"

      - name: Dummy test step
        run: echo "Tests passed successfully!"
